In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
print(np.__version__)

2.1.3


In [7]:
arr = np.array([1,2,3,4,5,])

In [8]:
arr

array([1, 2, 3, 4, 5])

In [12]:
type(arr)

numpy.ndarray

In [21]:
a = [6,22,22,44,55,66,]

In [22]:
a

[6, 22, 22, 44, 55, 66]

In [25]:
print(a * 2)

[6, 22, 22, 44, 55, 66, 6, 22, 22, 44, 55, 66]


In [9]:
age = np.array([22,33,55,66])

In [10]:
age

array([22, 33, 55, 66])

In [11]:
print(age * 2)

[ 44  66 110 132]


In [14]:
arr2d = np.array([[1,2,3,4],[5,6,7,8,]])

In [15]:
arr2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr2d.ndim

2

In [21]:
arr3d = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])

In [22]:
arr3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [23]:
arr3d.ndim

3

In [ ]:
# pip list

In [25]:
arr3d.sum(axis=1)

array([[15, 18, 21, 24]])